USE [master]
GO

/****** Object:  Database [WorkingTime]    Script Date: 2022.05.24. 11:14:17 ******/
CREATE DATABASE [WorkingTime]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WorkingTime', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WorkingTime.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WorkingTime_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WorkingTime_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WorkingTime].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WorkingTime] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WorkingTime] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WorkingTime] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WorkingTime] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WorkingTime] SET ARITHABORT OFF 
GO

ALTER DATABASE [WorkingTime] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WorkingTime] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WorkingTime] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WorkingTime] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WorkingTime] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WorkingTime] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WorkingTime] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WorkingTime] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WorkingTime] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WorkingTime] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WorkingTime] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WorkingTime] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WorkingTime] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WorkingTime] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WorkingTime] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WorkingTime] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WorkingTime] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WorkingTime] SET RECOVERY FULL 
GO

ALTER DATABASE [WorkingTime] SET  MULTI_USER 
GO

ALTER DATABASE [WorkingTime] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WorkingTime] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WorkingTime] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WorkingTime] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WorkingTime] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WorkingTime] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WorkingTime] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WorkingTime] SET  READ_WRITE 
GO


