USE [WorkingTime]

GO

SET ANSI_PADDING ON


GO

CREATE NONCLUSTERED INDEX [IX_Employee_EmployeeName] ON [dbo].[Employee]
(
	[EmployeeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO
----------------------------------

USE [WorkingTime]

GO

SET ANSI_PADDING ON


GO

CREATE NONCLUSTERED INDEX [IX_Job_JobName] ON [dbo].[Job]
(
	[JobName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO

